---

vsphere:
  hostname: "{{ vault_vsphere_hostname }}"
  username: "{{ vault_vsphere_username }}"
  password: "{{ vault_vsphere_password }}"
  datacenter: SWD
  cluster: SWD Infrastructure
  datastore: nfs_nappaff_swd_build_03
  folder: Infrastructure/Infra/RD/Infra/Kubernetes
  resource_pool: RD_Infra
  network: LAN Build
  domain: "{{ vault_vsphere_domain }}"

  controller:
    template: template_xenial_k8s_controller
  worker:
    template: template_xenial_k8s_worker
    disk_size_gb: 500

  instance_user: rdadm
  instance_ssh_private_key: ~/id_rsa_rdadm
