---

- name: Preparation for kubespray
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Copy template for hosts.ini
      copy:
        src: hosts.ini.template
        dest: hosts.ini

    - name: Add to section all
      lineinfile:
        path: hosts.ini
        insertafter: '^\[all\]$'
        line: "{{ item }} ansible_host={{ hostvars[item]['node']['instance']['ipv4'] }} ip={{ hostvars[item]['node']['instance']['ipv4'] }}"
      with_items: "{{ groups['k8s'] }}"

    - name: Add to section controller
      lineinfile:
        path: hosts.ini
        insertafter: '^\[controller\]$'
        line: "{{ item }}"
      with_items: "{{ groups['controller'] }}"

    - name: Add to section worker
      lineinfile:
        path: hosts.ini
        insertafter: '^\[worker\]$'
        line: "{{ item }}"
      with_items: "{{ groups['worker'] }}"

    - name: Add to section dmz
      lineinfile:
        path: hosts.ini
        insertafter: '^\[dmz\]$'
        line: "{{ item }}"
      with_items: "{{ groups['dmz'] }}"
