---

- name: Sanity checks
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Check Ansible version
      assert:
        that: 'ansible_version.full is version_compare("2.7.4", ">=")'
        msg: 'Broken set_fact (https://www.jeffgeerling.com/blog/2017/adding-strings-array-ansible)'

    - name: Install prerequisites for vSphere
      pip:
        name:
          - PyVmomi
      become: yes
