---

- name: Sanity checks
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/global.yml
    - vars/hcloud/vars.yml
    - vars/hcloud/vault.yml
  tasks:

    - name: Check Ansible version
      assert:
        that: 'ansible_version.full is version_compare("2.8.4", ">=")'
        msg: 'Modules for Hetzner Cloud are only included in >=2.8'

    - name: Download CLI for Hetzner Cloud
      unarchive:
        src: "https://github.com/hetznercloud/cli/releases/download/v{{ hcloud.cli_version }}/hcloud-linux-amd64-v{{ hcloud.cli_version }}.tar.gz"
        dest: "/tmp/"
        remote_src: yes
      delegate_to: localhost

    - name: Install CLI for Hetzner Cloud
      file:
        src: "/tmp/hcloud-linux-amd64-v{{ hcloud.cli_version }}/bin/hcloud"
        dest: "{{ hcloud.cli_path }}"
        remote_src: yes
      delegate_to: localhost

    - name: Install python library for Hetzner Cloud
      pip:
        name:
          - hcloud
      become: yes
