---

- name: Provision nodes
  hosts: k8s
  gather_facts: no
  serial: 3
  vars_files:
    - vars/auth.yml
    - vars/global.yml
  any_errors_fatal: true
  roles:

    - role: provision-vsphere

    - role: provision-ssh-config

    - role: docker-volume
