---

- name: Prepare environment
  hosts: localhost
  gather_facts: no
  vars:
    hcloud_module_version: 0.3.2
  tasks:
    - name: Ensure library directory is present
      file:
        path: library
        state: directory
    - name: Install modules for Hetzner Cloud
      unarchive:
        src: "https://github.com/thetechnick/hcloud-ansible/releases/download/v{{ hcloud_module_version }}/hcloud-ansible_v{{ hcloud_module_version }}_linux_amd64.zip"
        dest: library
        remote_src: yes

- name: Provision nodes
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/hcloud/vars.yml
    - vars/hcloud/vault.yml
  tasks:
    - hcloud_server:
        name: "{{ vm_list }}"
        image: "{{ hcloud.image }}"
        server_type: "{{ hcloud.server_type }}"
        location: "{{ hcloud.location }}"
        ssh_keys: "{{ hcloud.ssh_keys }}"
        token: "{{ hcloud.token }}"
      register: nodes
    - add_host:
        name: "{{ item.name }}"
        ansible_host: "{{ item.public_ipv4 }}"
        ansible_user: root
        ansible_ssh_private_key_file: "{{ hcloud.ssh_private_key }}"
        hcloud_server_id: "{{ item.id }}"
        groups:
          - k8s
      with_items: "{{ nodes.servers }}"
  tags:
    - provision

- name: Create SSH config
  hosts: k8s
  gather_facts: no
  tasks:
    - copy:
        content: |
          # config for {{ inventory_hostname }}
          Host {{ inventory_hostname }}
              HostName {{ ansible_host }}
              User {{ ansible_user }}
              IdentityFile {{ ansible_ssh_private_key_file }}
              StrictHostKeyChecking no
              UserKnownHostsFile /dev/null
        dest: "~/.ssh/config.d/hcloud_{{ inventory_hostname }}"
        mode: "0640"
      delegate_to: localhost
  tags:
    - provision

- name: Prepare nodes for Ansible
  hosts: k8s
  gather_facts: no
  tasks:
    - name: Wait for SSH to be available
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        connect_timeout: 5
        timeout: 60
      delegate_to: localhost
    - name: Making sure no other apt-get task is running
      raw: "while lsof /var/lib/apt/lists/lock; do sleep 5; done"
    - name: Making sure no other dpkg task is running
      raw: "while lsof /var/lib/dpkg/lock-frontend; do sleep 5; done"
    - name: Install updates
      raw: "apt-get update && apt-get -y upgrade"
    - name: Install Python
      raw: "apt-get -y install python-pip jq"
  tags:
    - provision

- name: Manage volume
  hosts: k8s
  vars:
    hcloud_path: ~/.local/bin/
  vars_files:
    - vars/global.yml
    - vars/hcloud/vars.yml
    - vars/hcloud/vault.yml
  tasks:
    - name: Create volumes
      include_tasks: provision_hcloud_volume.yml
      when: 'hcloud.use_volumes'
  tags:
    - provision
