---

- name: Provision nodes
  hosts: k8s
  gather_facts: no
  serial: 3
  any_errors_fatal: true
  roles:

    - role: provision-vsphere

    - role: provision-ssh-config

    - role: docker-volume

  tasks:

    - name: Create directory for debugging
      file:
        path: debug
        state: directory
      delegate_to: localhost
      run_once: yes

    - name: Store hostvars
      copy:
        dest: "debug/provision_{{ inventory_hostname }}.yml"
        content: "{{ hostvars[inventory_hostname] | to_nice_json(indent=2) }}"
      delegate_to: localhost