---

- name: Create and attach volume
  hcloud_volume:
    name: "{{ inventory_hostname }}-docker"
    size: 20
    server: "{{ inventory_hostname }}"
    api_token: "{{ hcloud.token }}"
  delegate_to: localhost
